<script src="javascript/jquery-2.2.0.min.js?v=1"></script>
<script src="javascript/jquery.dynatable.js?v=1"></script>
<script src="javascript/bootstrap-3.3.6.min.js?v=1"></script>
<script src="javascript/moment-2.11.1-min.js?v=1"></script>
<script src="javascript/moment-hijri.js?v=1"></script>
<script src="javascript/hijriDate.js?v=1"></script>
<script src="javascript/index.js?v=1"></script>
<script src="src/custom.js?v=1"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
