<?php
include('connection.php');
include('_authCheck.php');
require '../vendor/autoload.php'; 

use Dompdf\Dompdf;

$receiptTemplate = file_get_contents("receipt.html");
// echo "<pre>";
// echo $receiptTemplate; exit;
$sql = "select * from receipts ORDER BY Receipt_No ASC";
$result= mysqli_query($link,$sql);
// echo "<pre>";
$ntw = new \NTWIndia\NTWIndia();
$pdfContent = "";
while($values = mysqli_fetch_assoc($result))
{
    $thaliDetailsSql = "select ITS_No from thalilist WHERE Thali = '" . $values['Thali_No'] . "'";
    $thaliDetails= mysqli_fetch_assoc(mysqli_query($link,$thaliDetailsSql));

    $paymentType = $values['payment_type'] == 'Cash' ? "CASH" : "ONLINE";

    $paymentDetails = '';

    if($paymentType == 'ONLINE') {
        $paymentDetails = '<div>Transaction Reference: <span style="font-weight: bold;text-transform: capitalize;text-transform: uppercase;">'.$values['trasaction_id'].'</span></div>';
    } else {
        $paymentDetails = '<div>Receipt Generated By: <span>'.$values['received_by'].'</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sign: </div>';
    }

    $array_from_to = array (
        '{RECEIPT_NO}' => $values['Receipt_No'],
        '{THALI_NO}' => $values['Thali_No'],
        '{RECEIPT_DATE}' => $values['created'],
        '{ITS_NO}' => $thaliDetails['ITS_No'],
        '{NAME}' => $values['name'],
        '{AMOUNT}' => $values['Amount'],
        '{AMOUNT_IN_WORDS}' => $ntw->numToWord( $values['Amount'] ),
        '{PAYMENT_TYPE}' => $paymentType,
        '{PAYMENT_DETAILS}' => @$paymentDetails
    );
    // print_r($array_from_to);
    $pdfContent .=  str_replace(array_keys($array_from_to), $array_from_to, $receiptTemplate);
    // strstr($receiptTemplate, $array_from_to);
}

// exit(0);

$dompdf = new Dompdf();

$dompdf->loadHtml($pdfContent);

// $dompdf->setPaper('A4', 'landscape');
$dompdf->setPaper(array(0,0,720,550));
$dompdf->render();
$dompdf->stream("",array("Attachment" => false));


// $dompdf->stream("attach.pdf",array("Attachment" => false));


// $output = $dompdf->output();
// file_put_contents('Brochure.pdf', $output);
exit(0);