<?php
require_once '../vendor/autoload.php'; 

function getReceiptHtml($link, $receiptTemplate, $receiptDetails) {
    
    $ntw = new \NTWIndia\NTWIndia();
    $thaliDetailsSql = "select ITS_No, Full_Address from thalilist WHERE Thali = '" . $receiptDetails['Thali_No'] . "'";
    $thaliDetails= mysqli_fetch_assoc(mysqli_query($link,$thaliDetailsSql));

    $paymentType = $receiptDetails['payment_type'] == 'Cash' ? "CASH" : "ONLINE";

    $paymentDetails = '';
    $bottomTitle = '';

    if($paymentType == 'ONLINE') {
        $paymentDetails = '<div>Transaction Reference: <span style="font-weight: bold;text-transform: capitalize;text-transform: uppercase;">'.$receiptDetails['trasaction_id'].'</span></div>';
        $bottomTitle = '<div>This receipt is auto-generated and does not require a signature.</div>';
    } else {
        $paymentDetails = '<div>Receipt Generated By: <span>'.$receiptDetails['received_by'].'</span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sign: </div>';
    }

    $array_from_to = array (
        '{RECEIPT_NO}' => $receiptDetails['Receipt_No'],
        '{THALI_NO}' => $receiptDetails['Thali_No'],
        '{RECEIPT_DATE}' => $receiptDetails['created'],
        '{ITS_NO}' => $thaliDetails['ITS_No'],
        '{NAME}' => $receiptDetails['name'],
        '{AMOUNT}' => $receiptDetails['Amount'],
        '{AMOUNT_IN_WORDS}' => $ntw->numToWord( intval($receiptDetails['Amount']) ),
        '{PAYMENT_TYPE}' => $paymentType,
        '{PAYMENT_DETAILS}' => $paymentDetails,
        '{BOTTOM_TITLE}' => $bottomTitle,
        '{ADDRESS}' => $thaliDetails['Full_Address']
    );
    return  str_replace(array_keys($array_from_to), $array_from_to, $receiptTemplate);
}